### ISSUE TITLE
Ajánlatkérés egyeztetés

### ISSUE THREAD

**Issue by gimjong** [sturmannpal/RFT#1]
Ajánlatkérés vázlatot ki kell egészíteni, nem csak árra koncentrálni benne.

**Comment by gimjong** [comment]
{nem tudom Zsókához rendelni ezt az issuet, Palival egyeztetés alatt} #2 issueban

**Comment by gimjong** [comment]
Az ajánlatkérés vázlat inkább csak árajánlat kérés, nem tartalmazza jelenleg elég részletesen a követelmény specifikációt, ezt kellene javítani.

**Comment by sturmannpal** [comment]
Megtalálom itt valahol ezt az ajánlatkérést?

**Comment by gimjong** [comment]
Javítok rajta és csatolom ehhez az issue-hoz.

**Comment by sturmannpal** [comment]
Csatoltad már és nem találom, vagy még nem?

**Comment by gimjong** [comment]
Holnap csatolom a javított verziót.

**Comment by Keresztury** [comment]
[ÁRAJÁNLAT-KÉRÉS.docx](https://github.com/sturmannpal/RFT/files/1603902/ARAJANLAT-KERES.docx)
Ezt raktam össze, ha megérkezik a specifikáció, ezzel kellene összedolgozni, egy ajánlatkéréssé.

**Comment by gimjong** [comment]
[Akasztofa_specifikáció.docx](https://github.com/sturmannpal/RFT/files/1604116/Akasztofa_specifikacio.docx)
Csatoltam a specifikációt, a vége tartalmazza a becslést.
Pali, az ajánlatkérést ehhez kellene igazítani, és összedolgozni egy dokumentummá.

**Comment by gimjong** [comment]
Ajánlatkérés tartalmazza: bevezetés (ezt beleraktam a specifikációba), ajánlatkérő bemutatása, követelmény specifikáció (ez maga a speci). Árajánlatot kell adni (a speci becslés fejezete, számszerűsítsük is?).

**Comment by gimjong** [comment]
[Akasztofa_specifikáció.docx](https://github.com/sturmannpal/RFT/files/1604169/Akasztofa_specifikacio.docx)
eltűnt a szerzők leírása, javítottam. (ez a dokumentum a követelményspecifikáció)

**Comment by Keresztury** [comment]
[Akasztofa_árajánlat.docx](https://github.com/sturmannpal/RFT/files/1635741/Akasztofa_arajanlat.docx)
Az árajánlat.
