### ISSUE TITLE
Hol van Zsóka

### ISSUE THREAD

**Issue by gimjong** [sturmannpal/RFT#2]
Szia Pali! Zsóka userét nem látom sehol itt a gitben, tudok tenni valamit, hogy lássam? Nem adtad hozzá a projekthez?
Köszi
Zita

**Comment by sturmannpal** [comment]
Szia Zita,

Zsóka azóta is meg van hívva, de még nem fogadta el a meghívást... 

Pali

**Comment by gimjong** [comment]
Köszi!
