### ISSUE TITLE
Teszt jegyzőkönyvek

### ISSUE THREAD

**Issue by gimjong** [sturmannpal/RFT#8]

**Comment by Keresztury** [comment]
[Akasztofa_tesztjegyzőkönyv_11-es hiba.docx](https://github.com/sturmannpal/RFT/files/1635641/Akasztofa_tesztjegyzokonyv_11-es.hiba.docx)

**Comment by sturmannpal** [comment]
[Akasztofa_tesztjegyzőkönyv_14-es hiba.docx](https://github.com/sturmannpal/RFT/files/1636101/Akasztofa_tesztjegyzokonyv_14-es.hiba.docx)
